modified the function definitions to allow a custom smtp-from
gophish/gomail pull request #2
Opened 2018-02-27 11:27 UTC by ChessSpider

required for https://github.com/gophish/gophish/pull/986  (see for discussion)

2018-02-27 14:59 UTC, jordan-wright commented
Hey @ChessSpider! Thanks for sending this over.

I appreciate you taking the time to make a first pass at this. Let me review things a bit more, only because changing the function signature of an exported function is a pretty big deal since it breaks backwards incompatibility. It's possible that we could modify either the `Message` or the `Sender` instead to add a parameter that supports the envelope sender.

I'll keep you posted over the next couple of days, as time hopefully frees up for me to work on this. 😄

2018-02-27 15:17 UTC, ChessSpider commented
hey Jordan, sure no worries it's your party.  I agree 100% breaking the signature is not a good idea. Probably better to add another function. But I wasn't sure what the best name would be. I was a bit disappointed that Go doesn't support method-overloading. 

I didn't opt for changing the ``Message`` due to it represents the actual Envelope to be sent.

I didn't change the ``Sender`` because there's quite some abstraction-logic there, and it seems to be solely meant for setting up the SMTP-Connection to the server. There's no logic there for sending email as a specific user (as Message is meant for that, but that isn't useful for this use-case)

As the methods used internally already had a From and a To[] which did specifically what I wanted, I chose to do something with that instead.

In any case, have a look and tell me how you'd like to see it. 

tldr; My suggestion is to revert the changed signature back, and add another method which allows for a custom SMTP-From.  

Ideally, the new method also allows for having a different SMTP-To and a different Envelope-To. This means you can set the Envelope-To to e.g. 'undisclosed-recipient' while it still arrives in your inbox.   

Please advise 👍

2018-03-01 08:15 UTC, ChessSpider commented
> tldr; My suggestion is to revert the changed signature back, and add another method which allows for a custom SMTP-From.

I have done this now

> Ideally, the new method also allows for having a different SMTP-To and a different Envelope-To. This means you can set the Envelope-To to e.g. 'undisclosed-recipient' while it still arrives in your inbox.

It still cannot do this. But I don't know what the Go-way of approaching this would be.

2018-03-01 12:03 UTC, ChessSpider commented
Hi, 
I also snug in automatic generation of message-id per message.. my own anti-spam solution mentioned that as one of the reasons why a message may be spam. 
Because it has to be unique per message I wasn't really sure where else to put it.

2018-03-02 03:14 UTC, jordan-wright requested changes
Hey @ChessSpider, this is looking good! It seems that adding the `SendCustomFrom` is about as good as we can do, so that works for me.

I've added a few comments. The biggest thing is that we'll want to move the message ID generation to another separate pull request later down the line.

Thanks again for your work on this. I think we're in the home stretch here! 😄

2018-03-02 03:14 UTC, jordan-wright commented on send.go
> +func CreateRandomMessageId(email string) string {
I'd prefer if this could be a separate pull request, since it would require more testing and review. It's easiest to review just one piece of functionality at a time. One way you could accomplish this is to create a new branch off your branch that already has the envelope changes and move the message ID bits there.

Also, if you're looking for a message ID generator, I wrote one for a different email library [here](https://github.com/jordan-wright/email/blob/master/email.go#L580) that we could consider using.

2018-03-02 03:14 UTC, jordan-wright commented on smtp_test.go
> +func doTestSMTPReset(t *testing.T, d *Dialer, want []string) {
If possible, could you add a test to ensure that `SendCustomFrom` is doing what you expect it to do? At the very least, we'll want to make sure that the `MAIL FROM` is what we expect and the `From` header is still the from the message.

2018-03-08 15:55 UTC, ChessSpider commented
@jordan-wright like this?

2018-03-14 01:03 UTC, jordan-wright commented
Looks good to me! Thanks for adding in that test.

2018-03-14 01:03 UTC, jordan-wright approved these changes

2018-03-14 01:03 UTC, merged